#!/bin/bash
# branches=()
# eval "$(git for-each-ref --shell --format='branches+=(%(refname))' refs/heads/)"
# for branch in "${branches[@]}"; do
#   echo "${branch}"
# done
#



for BRANCH in `git branch --list|sed 's/\*//g'`;
  do
    git checkout $BRANCH
    git add .
    git ci -am"chore"
    git push origin $BRANCH
  done
